name: data_burger
description: "Control de Stock para Hamburgueseria"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  csv: ^6.0.0
  excel: ^4.0.6
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
